FROM alpine:3.7

# Install packages
RUN sed -i -e 's/dl-cdn/dl-4/' /etc/apk/repositories && \
    apk --no-cache add \
    php7 \
    php7-fpm \
    php7-mysqli \
    php7-json \
    php7-openssl \
    php7-curl \
    php7-zlib \
    php7-xml \
    php7-phar \
    php7-intl \
    php7-dom \
    php7-xmlreader \
    php7-ctype \
    php7-mbstring \
    php7-gd \
    nginx \
    supervisor \
    curl \
    php7-session

RUN apk --no-cache add \
    php7-tokenizer

LABEL Maintainer="Robson P Oliveira <rpopuc.dev@gmail.com>" \
      Description="Lightweight container with Nginx 1.12 & PHP-FPM 7.2 based on Alpine Linux."



# RUN set -x ; \
#   addgroup -g 82 -S www-data ; \
#   adduser -u 82 -D -S -G www-data www-data && exit 0 ;

# Configure nginx
COPY config/nginx.conf /etc/nginx/nginx.conf

# Configure PHP-FPM
COPY config/fpm-pool.conf /etc/php7/php-fpm.d/zzz_custom.conf
COPY config/php.ini /etc/php7/conf.d/zzz_custom.ini

# Configure supervisord
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Add application
RUN mkdir -p /var/www/public
RUN echo "<?php phpinfo();" > /var/www/public/index.php

RUN adduser -u 82 -D -S -G www-data www-data

RUN chown -R www-data /var/www/public

WORKDIR /var/www/

EXPOSE 80 443

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
